### ISSUE TITLE
How to run SigProfilerExtractor with GPU

### ISSUE THREAD

**Issue by YingYa** [AlexandrovLab/SigProfilerExtractor#102] opened 2021-11-03 10:15 UTC
Hi,

I run sigProfilerExtractor with 'gpu=True', but program interrupted after finished 'Extracting signature 1'.

**when 'batch_size=1', the error occured:**
_File "/path/to/lib/python3.9/site-packages/SigProfilerExtractor/subroutines.py", line 810, in decipher_signatures
    H = results[j][1]
IndexError: list index out of range_

**when 'batch_size=2', the error occured:**
_File "/path/to/lib/python3.9/site-packages/SigProfilerExtractor/subroutines.py", line 811, in decipher_signatures
    converge_information[j,:] = results[j][2][:]
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1._

Thnaks

**Comment by mdbarnesUCSD** [comment] 2021-11-16 21:53
Working with @YingYa via e-mail to resolve this issue. Will provide more information here once the issue has been resolved in case any other users encounter the same issue.

**Comment by mdbarnesUCSD** [comment] 2021-12-02 00:45
The 1.1.4 release had updates for random matrix initialization used for Pytorch GPU and introduced this bug for using batch_size greater than 1. The issue is resolved in commit e97e341.

**Closed by mdbarnesUCSD** 2021-12-02 00:45 UTC
