### ISSUE TITLE
Problem with COSMIC Decomposition

### ISSUE THREAD

**Issue by amootta** [AlexandrovLab/SigProfilerExtractor#166] opened 2022-10-31 15:55 UTC
Hello there, 
I am running SigProfilerExtractor through Sigminer (https://github.com/ShixiangWang/sigminer). 
I have a question about the COSMIC decomposition results that I am receiving. 
In my suggested solutions output file, I am looking at the COSMIC_SBS96_Decomposed_Solution file and its outputs. I thought that the signatures resulting in this folder would be those that have been matched to COSMIC, eg. SBS39 would mean that it has deconvoluted my signature to the COSMIC signature SBS39. However, like the above, the signatures are completely different!

This is SBS39 in my output:
![image](https://user-images.githubusercontent.com/32172683/199051197-98b89b60-62b6-4c1a-a9ff-41b23b5ab039.png)

Which is different to SBS39 on COSMIC:
![image](https://user-images.githubusercontent.com/32172683/199051258-4de9198b-546a-4ded-9039-533216f7480d.png)

I have been in touch with the creator of Sigminer, and we found that actually it seems that the correct C>G mutations have been changed to C>T in SBS39. We can see the same happen with SBS18 results shown below, where correct C>A mutations have been changed to T>C in SBS18. 

My 'SBS18' signature:
![image](https://user-images.githubusercontent.com/32172683/199051529-339c7c03-796f-4e60-8598-068459255b50.png)

The COSMIC SBS18 Signature: 
![image](https://user-images.githubusercontent.com/32172683/199052257-43b10cb5-51d5-4f91-a9d5-c84dc2d46e75.png)

I have checked the data of the signatures itself (I read in the SBS96/Suggested_Solution/COSMIC_SBS96_Decomposed_Solution/Signatures/COSMIC_SBS96_Signatures.txt file) and it seems that the problem does stem from the data, rather than with pltoting. E.g. With SBS39 in the data, C>T changes are the most common, like that shown in the plot. I then went back to the tally data, and also found that C>T changes are most frequent across most samples. So I believe the problem comes with associating the decomposed solutions to COSMIC signatures – these become incorrect. I have tried with SigPRofilerExtractor version 1.1.4 and the same results are seen.

I tried to manually fit the signatures found in the SBS_96_decomposed_solution folder, and it fit to completely different COSMIC signatures too. E.g. what is named ‘SBS39’ is most similar to SBS30, etc. 

Please could you let me know what this all means or if you want me to send you some data. 

Thanks very much

**Comment by ShixiangWang** [comment] 2022-11-01 02:03
As Sigminer only provides a wrapper of SigProfilerExtractor, so the issue comes from SigProfiler itself. The **wrongly labelled** 96 signature matrix seems affect the decomposition result, please take a careful check and see if a quick fix can be taken. :)

**Comment by mdbarnesUCSD** [comment] 2022-11-03 04:38
Hi @amoota,

If you are able to produce this issue when directly running SigProfilerExtractor, then please provide your input matrix as well as the JOB_METADATA.txt so that we can reproduce the issue.

It looks like your input matrix has rows that are out of order. Please verify that your input matrix has the correct indexing for the rows by comparing to a [properly formatted file for the SBS96 context here](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/references/matrix/BRCA_example/BRCA_example.SBS96.all).

Thanks!

**Comment by ShixiangWang** [comment] 2022-11-08 02:25
This issue is due to the unorder mutation types, thanks to @mdbarnesUCSD for the great observation. As many users of SigProfiler may be not familiar with mutation type orders, I suggest an order check shall be used when a user inputs a matrix so the same issue can be easily tracked in SigProfiler or its wrapper.

This issue can be closed as it fixed. @amootta @mdbarnesUCSD 

Best.

**Closed** 2022-11-08 10:09 UTC
